[build]
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  OPENROUTE_API_KEY = "eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6IjMyMjE4MWZhN2EyMzRjOTY5MjRjOTYyMTNjN2I1YTE0IiwiaCI6Im11cm11cjY0In0="
  FIREBASE_API_KEY = "AIzaSyCboNnTkG1PxSdOcXmzY8usWAB5cg2Hcso"
  FIREBASE_AUTH_DOMAIN = "atupuerta-788b4.firebaseapp.com"
  FIREBASE_PROJECT_ID = "atupuerta-788b4"
  FIREBASE_STORAGE_BUCKET = "atupuerta-788b4.firebasestorage.app"
  FIREBASE_MESSAGING_SENDER_ID = "262332454801"
  FIREBASE_APP_ID = "1:262332454801:web:6695fe80b8e45611e7ec30"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true 
